---
title: "Project Proposal"
output: html_notebook
---

## Section 1. Introduction
Our general research topic is to determine the level of sodium in admitted patients. Throughout the data, the sodium level is either flagged or not, further variables would describe the admitted patients' sodium level as low, normal, or high.

Based on the data provided, the purpose of our research is to determine the median age of each level of sodium.

## Section 2. Data Analysis Plan
First look over excel spreadsheet with the hospital data. Determine whether the patient sodium level is flagged 'Yes' or 'No', then determine if the patient has a low, normal, or high sodium level. After determining whether the patient is flagged 'Yes' or 'No', determine the median age for the respective sodium level of low, normal, or high. 

## Section 3. Data
https://flpoly-my.sharepoint.com/:x:/r/personal/jpolur1487_floridapoly_edu/_layouts/15/Doc.aspx?sourcedoc=%7B7FC3B36F-806A-40E4-9A4C-BB901878B6E0%7D&file=Deidentified%20HSE%20data%20table_no%20severity(2).xlsx&action=default&mobileredirect=true

